/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import controller.LoginController;
import controller.OrderController;
import controller.ServiceController;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Karyawan;
import model.Layanan;
import model.OrderData;

/**
 *
 * @author ariqn
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    CardLayout cardLayout;
    private Karyawan currentKaryawan;
    private DefaultTableModel tableModel;
    private String[][] rowData;
    
    public Index() {
        currentKaryawan = new Karyawan(0, "Unknown", "Unknown", "");
        initComponents();
        OrderController.populateList(serviceForm);
        transactionDateField.setEditable(false);
        cardLayout = (CardLayout) mainContent.getLayout();
        this.setLocationRelativeTo(null);
        this.setTitle("Kumbah");
    }
    
    public Index(Karyawan currentKaryawan) {
        this.currentKaryawan = currentKaryawan;
        initComponents();
        OrderController.populateList(serviceForm);
        transactionDateField.setEditable(false);
        cardLayout = (CardLayout) mainContent.getLayout();
        this.setLocationRelativeTo(null);
        this.setTitle("Kumbah");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSplitPane1 = new javax.swing.JSplitPane();
        sidebar = new javax.swing.JPanel();
        addOrderBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        serviceBtn = new javax.swing.JButton();
        editOrderBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        mainContent = new javax.swing.JPanel();
        addOrderPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameForm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        weightForm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        serviceForm = new javax.swing.JComboBox<>();
        createOrderBtn = new javax.swing.JButton();
        orderPnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        transactionDateField = new javax.swing.JTextField();
        customerField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        finishOrderBtn = new javax.swing.JButton();
        servicePnl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        addServiceBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        serviceNameField = new javax.swing.JTextField();
        servicePriceField = new javax.swing.JTextField();
        editServiceBtn = new javax.swing.JButton();
        refreshServiceBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(103, 98, 211));
        sidebar.setPreferredSize(new java.awt.Dimension(150, 540));

        addOrderBtn.setBackground(new java.awt.Color(103, 98, 211));
        addOrderBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        addOrderBtn.setText("Add Order");
        addOrderBtn.setBorder(null);
        addOrderBtn.setBorderPainted(false);
        addOrderBtn.setContentAreaFilled(false);
        addOrderBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOrderBtn.setPreferredSize(new java.awt.Dimension(73, 40));
        addOrderBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addOrderBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KUMBAH");

        serviceBtn.setBackground(new java.awt.Color(178, 173, 245));
        serviceBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        serviceBtn.setForeground(new java.awt.Color(255, 255, 255));
        serviceBtn.setText("Service");
        serviceBtn.setBorder(null);
        serviceBtn.setContentAreaFilled(false);
        serviceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                serviceBtnActionPerformed(evt);
            }
        });

        editOrderBtn.setBackground(new java.awt.Color(178, 173, 245));
        editOrderBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        editOrderBtn.setText("Orders");
        editOrderBtn.setBorder(null);
        editOrderBtn.setBorderPainted(false);
        editOrderBtn.setContentAreaFilled(false);
        editOrderBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editOrderBtn.setPreferredSize(new java.awt.Dimension(71, 40));
        editOrderBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editOrderBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(103, 98, 211));
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(editOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(serviceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jSplitPane1.setLeftComponent(sidebar);

        mainContent.setBackground(new java.awt.Color(249, 249, 249));
        mainContent.setLayout(new java.awt.CardLayout());

        addOrderPnl.setBackground(new java.awt.Color(249, 249, 249));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 98, 211));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Order");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setLabelFor(nameForm);
        jLabel5.setText("Name");

        nameForm.setBackground(new java.awt.Color(248, 250, 252));
        nameForm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameForm.setForeground(new java.awt.Color(0, 0, 0));
        nameForm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setLabelFor(serviceForm);
        jLabel6.setText("Service");

        weightForm.setBackground(new java.awt.Color(248, 250, 252));
        weightForm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        weightForm.setForeground(new java.awt.Color(0, 0, 0));
        weightForm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setLabelFor(weightForm);
        jLabel7.setText("Laundry Weight");

        serviceForm.setBackground(new java.awt.Color(248, 250, 252));
        serviceForm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        serviceForm.setForeground(new java.awt.Color(0, 0, 0));
        serviceForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createOrderBtn.setBackground(new java.awt.Color(137, 128, 245));
        createOrderBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        createOrderBtn.setText("Add");
        createOrderBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                createOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addOrderPnlLayout = new javax.swing.GroupLayout(addOrderPnl);
        addOrderPnl.setLayout(addOrderPnlLayout);
        addOrderPnlLayout.setHorizontalGroup(
            addOrderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
            .addGroup(addOrderPnlLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(addOrderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addOrderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(nameForm, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(weightForm, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(serviceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addOrderPnlLayout.setVerticalGroup(
            addOrderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderPnlLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameForm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weightForm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(createOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );

        mainContent.add(addOrderPnl, "addOrderPnl");

        orderPnl.setBackground(new java.awt.Color(249, 249, 249));

        jScrollPane3.setBackground(new java.awt.Color(249, 249, 249));
        jScrollPane3.setForeground(new java.awt.Color(249, 249, 249));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 98, 211));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Orders");

        orderTable.setBackground(new java.awt.Color(249, 249, 249));
        orderTable.setForeground(new java.awt.Color(0, 0, 0));
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Transaction Date", "Finished Date", "Customer", "Employee", "Total Price", "Quantity", "Service"
            }
        ));
        orderTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                orderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderTable);

        transactionDateField.setBackground(new java.awt.Color(248, 250, 252));
        transactionDateField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        customerField.setBackground(new java.awt.Color(248, 250, 252));
        customerField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Transaction Date");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Customer Name");

        finishOrderBtn.setBackground(new java.awt.Color(137, 128, 245));
        finishOrderBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        finishOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        finishOrderBtn.setText("Finish");
        finishOrderBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finishOrderBtn.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                finishOrderBtnMouseClicked(evt);
            }
        });
        finishOrderBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                finishOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(customerField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finishOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout orderPnlLayout = new javax.swing.GroupLayout(orderPnl);
        orderPnl.setLayout(orderPnlLayout);
        orderPnlLayout.setHorizontalGroup(
            orderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        orderPnlLayout.setVerticalGroup(
            orderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        mainContent.add(orderPnl, "orderPnl");

        servicePnl.setBackground(new java.awt.Color(249, 249, 249));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 98, 211));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Service");

        serviceTable.setBackground(new java.awt.Color(255, 255, 255));
        serviceTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        serviceTable.setForeground(new java.awt.Color(0, 0, 0));
        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "ID", "Name", "Price"
            }
        ));
        serviceTable.setGridColor(new java.awt.Color(248, 250, 252));
        serviceTable.setRowHeight(48);
        serviceTable.setSelectionBackground(new java.awt.Color(226, 232, 240));
        serviceTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        serviceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        serviceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        serviceTable.setShowHorizontalLines(true);
        serviceTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                serviceTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(serviceTable);

        addServiceBtn.setBackground(new java.awt.Color(137, 128, 245));
        addServiceBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addServiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        addServiceBtn.setText("Add Service");
        addServiceBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addServiceBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Service Name");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Price");

        serviceNameField.setBackground(new java.awt.Color(248, 250, 252));
        serviceNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        servicePriceField.setBackground(new java.awt.Color(248, 250, 252));
        servicePriceField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        editServiceBtn.setBackground(new java.awt.Color(137, 128, 245));
        editServiceBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editServiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        editServiceBtn.setText("Edit Service");
        editServiceBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editServiceBtnActionPerformed(evt);
            }
        });

        refreshServiceBtn.setBackground(new java.awt.Color(0, 0, 0));
        refreshServiceBtn.setForeground(new java.awt.Color(0, 0, 0));
        refreshServiceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/refresh.png"))); // NOI18N
        refreshServiceBtn.setText("Refresh table");
        refreshServiceBtn.setBorderPainted(false);
        refreshServiceBtn.setContentAreaFilled(false);
        refreshServiceBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                refreshServiceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(refreshServiceBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(servicePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshServiceBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel3);

        javax.swing.GroupLayout servicePnlLayout = new javax.swing.GroupLayout(servicePnl);
        servicePnl.setLayout(servicePnlLayout);
        servicePnlLayout.setHorizontalGroup(
            servicePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        servicePnlLayout.setVerticalGroup(
            servicePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        mainContent.add(servicePnl, "servicePnl");

        jSplitPane1.setRightComponent(mainContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderBtnActionPerformed
        OrderController.populateList(serviceForm);
        
        cardLayout.show(mainContent, "addOrderPnl");
    }//GEN-LAST:event_addOrderBtnActionPerformed
    
    private void serviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceBtnActionPerformed
        String[] header = {"ID", "Name", "Price"};
        
        tableModel = new DefaultTableModel(rowData, header);
        serviceTable.setModel(tableModel);
        TableColumnModel columnModel = serviceTable.getColumnModel();

//        set ukuran min dan max tabel
        columnModel.getColumn(0).setMaxWidth(40);
        
        ServiceController.index(tableModel);
        
        cardLayout.show(mainContent, "servicePnl");
    }//GEN-LAST:event_serviceBtnActionPerformed
    
    private void editOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderBtnActionPerformed
        String[] header = {"Transaction Date", "Finished Date", "Customer", "Employee", "Total Price", "Quantity", "Service"};
        
        tableModel = new DefaultTableModel(rowData, header);
        orderTable.setModel(tableModel);
        
        OrderController.index(tableModel);
        
        cardLayout.show(mainContent, "orderPnl");
    }//GEN-LAST:event_editOrderBtnActionPerformed
    
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LoginController.logout(this, currentKaryawan);
    }//GEN-LAST:event_logoutBtnActionPerformed
    
    private void addServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServiceBtnActionPerformed
        // TODO add your handling code here:
        AddService addService = new AddService(currentKaryawan);
        
        addService.setVisible(true);
    }//GEN-LAST:event_addServiceBtnActionPerformed
    
    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        // TODO add your handling code here:
        int row = orderTable.getSelectedRow();
        
        OrderData selectedData = OrderController.getListOrderData().get(row);
        
        transactionDateField.setText(selectedData.getTanggalTransaksi());
        customerField.setText(selectedData.getCustomerName());
    }//GEN-LAST:event_orderTableMouseClicked
    
    private void serviceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceTableMouseClicked
        // TODO add your handling code here:
        int row = serviceTable.getSelectedRow();
        
        Layanan selectedData = ServiceController.getListLayanan().get(row);
        
        serviceNameField.setText(selectedData.getNama());
        servicePriceField.setText(Long.toString(selectedData.getHarga()));
    }//GEN-LAST:event_serviceTableMouseClicked
    
    private void editServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editServiceBtnActionPerformed
        // TODO add your handling code here:
        int row = serviceTable.getSelectedRow();
        Layanan selectedData = ServiceController.getListLayanan().get(row);
        
        ServiceController.update(this, selectedData.getId(), serviceNameField.getText(), servicePriceField.getText(), tableModel);
        
        servicePriceField.setText("");
        serviceNameField.setText("");
    }//GEN-LAST:event_editServiceBtnActionPerformed
    
    private void refreshServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshServiceBtnActionPerformed
        // TODO add your handling code here:
        ServiceController.refresh(tableModel);
    }//GEN-LAST:event_refreshServiceBtnActionPerformed

    private void createOrderBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createOrderBtnActionPerformed
    {//GEN-HEADEREND:event_createOrderBtnActionPerformed
        OrderController.store(
                this, 
                nameForm.getText(), 
                weightForm.getText(), 
                serviceForm.getSelectedIndex() + 1, 
                currentKaryawan
        );
        
        nameForm.setText("");
        weightForm.setText("");
    }//GEN-LAST:event_createOrderBtnActionPerformed

    private void finishOrderBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_finishOrderBtnMouseClicked
    {//GEN-HEADEREND:event_finishOrderBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_finishOrderBtnMouseClicked

    private void finishOrderBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_finishOrderBtnActionPerformed
    {//GEN-HEADEREND:event_finishOrderBtnActionPerformed
        int row = orderTable.getSelectedRow();
        
        OrderData selectedData = OrderController.getListOrderData().get(row);
        
        OrderController.update(this, selectedData.getId(), tableModel);
        
        transactionDateField.setText("");
        customerField.setText("");
    }//GEN-LAST:event_finishOrderBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrderBtn;
    private javax.swing.JPanel addOrderPnl;
    private javax.swing.JButton addServiceBtn;
    private javax.swing.JButton createOrderBtn;
    private javax.swing.JTextField customerField;
    private javax.swing.JButton editOrderBtn;
    private javax.swing.JButton editServiceBtn;
    private javax.swing.JButton finishOrderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainContent;
    private javax.swing.JTextField nameForm;
    private javax.swing.JPanel orderPnl;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton refreshServiceBtn;
    private javax.swing.JButton serviceBtn;
    private javax.swing.JComboBox<String> serviceForm;
    private javax.swing.JTextField serviceNameField;
    private javax.swing.JPanel servicePnl;
    private javax.swing.JTextField servicePriceField;
    private javax.swing.JTable serviceTable;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextField transactionDateField;
    private javax.swing.JTextField weightForm;
    // End of variables declaration//GEN-END:variables
}
